[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lucas Roig", email = "lucas1.roig@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]",
]


[project.scripts]
api = "api:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
