[project]
name = "cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lucas Roig", email = "lucas1.roig@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "typer>=0.15.2",
]

[project.scripts]
cli = "cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
