[project]
name = "cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"

requires-python = ">=3.12"
dependencies = [
    "typer>=0.15.2",
    "prompt"
]

[project.scripts]
cli = "cli:main"

[tool.uv.sources]
prompt = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
